### ISSUE TITLE
If tss file exists, tasks will aborted due to warnings.

### ISSUE THREAD

**Issue by lis186** [Casear/Grunt-Jade2TSS#1]
Warning: Object #<Object> has no method 'convertArray' Use --force to continue.

**Comment by Casear** [comment]
Hi lis ,
Can you check which version you are using?
You need to use 0.7.4.
pls remove xml2tss too. 
I forked the xml2tss and added a method .
already pull request to xml2tss , but need to use my branch in a short time.
